### ISSUE TITLE
How to read a file line-by-line into a vector?

### ISSUE THREAD

**Issue by logankilpatrick** [logankilpatrick/JuliaStackOverflowCandidates#14]
Link to the original post (__Required if exists__):  
[How to read a file line-by-line into a vector?](https://stackoverflow.com/questions/3277503/how-to-read-a-file-line-by-line-into-a-list)

Question to be posted on StackOverflow (__Optional__) : 

Answer to be posted on StackOverflow (__Optional__) :

**Comment by StefanKarpinski** [comment]
I'm working on this one.

**Comment by StefanKarpinski** [comment]
https://stackoverflow.com/questions/58169711/how-to-read-a-file-line-by-line-in-julia/58169712#58169712

**Comment by logankilpatrick** [comment]
Looks awesome!
