### ISSUE TITLE
What is a macro and why use it? 

### ISSUE THREAD

**Issue by logankilpatrick** [logankilpatrick/JuliaStackOverflowCandidates#3]
Look for the answer

**Comment by logankilpatrick** [comment]
Why use it part was answered. Waiting for a response before I do a "How to use macros in Julia post".

**Comment by StefanKarpinski** [comment]
Links?

**Comment by logankilpatrick** [comment]
https://stackoverflow.com/questions/58137512/why-use-macros-in-julia
